import { test, expect } from '@playwright/test';

/**
 * Auto-generated by @arog
 * Date: 2026-01-17T05:10:32.035Z
 * Source: file:///Users/arog/Learn/arog/docs/arog-agent.html
 * Interactions captured: 6
 */


test('homepage loads correctly', async ({ page }) => {
  await page.goto('file:///Users/arog/Learn/arog/docs/arog-agent.html');
  await expect(page).toHaveTitle(/The AROG Story - Your Journey Begins/);
});

test('navigation to file:///Users/arog/Learn/arog/docs/arog-agent.html', async ({ page }) => {
  await page.goto('file:///Users/arog/Learn/arog/docs/arog-agent.html');
  await page.click('a:has-text("📖 AROG Agent You are here")');
  await expect(page).toHaveURL('file:///Users/arog/Learn/arog/docs/arog-agent.html');
});

test('button interaction', async ({ page }) => {
  await page.goto('file:///Users/arog/Learn/arog/docs/arog-agent.html');
  await page.click('button:has-text("Copy")');
  // Add assertions for button click results
});
