/**
 * AROG E2E Test Generator - Live Demo
 * 
 * This demonstrates @arog's ability to:
 * 1. Navigate to an application
 * 2. Explore the UI
 * 3. Generate tests automatically
 * 
 * Usage: Just tell @arog "generate E2E tests for my app"
 */

// Example: Auto-generated test based on UI exploration
// @arog explored http://localhost:8080 and found:

import { test, expect } from '@playwright/test';

test.describe('Auto-Generated Tests by @arog', () => {
  test('Homepage loads and displays main content', async ({ page }) => {
    // @arog navigated to homepage
    await page.goto('/');
    
    // @arog verified page loaded
    await page.waitForLoadState('networkidle');
    
    // @arog checked for main heading
    const heading = page.locator('h1').first();
    await expect(heading).toBeVisible();
    
    // @arog verified page title
    await expect(page).toHaveTitle(/.+/);
  });
  
  test('Navigation menu is functional', async ({ page }) => {
    await page.goto('/');
    
    // @arog found navigation links
    const navLinks = page.locator('nav a');
    const linkCount = await navLinks.count();
    
    // @arog verified links exist
    expect(linkCount).toBeGreaterThan(0);
    
    // @arog tested first link
    if (linkCount > 0) {
      await navLinks.first().click();
      await page.waitForLoadState('networkidle');
      
      // @arog verified navigation worked
      await expect(page).toHaveURL(/.+/);
    }
  });
  
  test('Interactive elements are clickable', async ({ page }) => {
    await page.goto('/');
    
    // @arog found buttons
    const buttons = page.locator('button');
    const buttonCount = await buttons.count();
    
    if (buttonCount > 0) {
      // @arog verified buttons are visible
      await expect(buttons.first()).toBeVisible();
      
      // @arog verified buttons are enabled
      await expect(buttons.first()).toBeEnabled();
    }
  });
  
  test('Forms can be filled and submitted', async ({ page }) => {
    await page.goto('/');
    
    // @arog looked for input fields
    const inputs = page.locator('input[type="text"], input[type="email"]');
    const inputCount = await inputs.count();
    
    if (inputCount > 0) {
      // @arog filled first input
      await inputs.first().fill('test@example.com');
      
      // @arog verified value was entered
      await expect(inputs.first()).toHaveValue('test@example.com');
    }
  });
  
  test('Page is responsive', async ({ page }) => {
    // @arog tested mobile viewport
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto('/');
    
    // @arog verified content is visible on mobile
    const body = page.locator('body');
    await expect(body).toBeVisible();
    
    // @arog tested tablet viewport
    await page.setViewportSize({ width: 768, height: 1024 });
    await expect(body).toBeVisible();
    
    // @arog tested desktop viewport
    await page.setViewportSize({ width: 1920, height: 1080 });
    await expect(body).toBeVisible();
  });
});

// These tests were automatically generated by @arog
// after exploring your application's UI structure
// 
// @arog used Playwright MCP to:
// - Navigate pages
// - Capture element snapshots  
// - Identify interactive elements
// - Generate meaningful test scenarios
//
// Want @arog to generate more tests?
// Just say: "@arog explore my app and add more test cases"
