import { test, expect } from '@playwright/test';

/**
 * Auto-generated by @arog
 * Date: 2026-01-17T04:46:50.727Z
 * Source: https://example.com
 * Interactions captured: 1
 */


test('homepage loads correctly', async ({ page }) => {
  await page.goto('https://example.com');
  await expect(page).toHaveTitle(/Example Domain/);
});
