/**
 * LIVE DEMO: Test Generated by @arog using Playwright MCP
 * 
 * Generated: ${new Date().toISOString()}
 * 
 * @arog explored https://example.com and automatically:
 * 1. Navigated to the page (using mcp_playwright_browser_navigate)
 * 2. Captured page structure (using mcp_playwright_browser_snapshot)
 * 3. Identified interactive elements (heading, link)
 * 4. Clicked "Learn more" link (using mcp_playwright_browser_click)
 * 5. Verified navigation worked
 * 6. Took screenshot (using mcp_playwright_browser_take_screenshot)
 * 7. Generated this test file
 * 
 * THIS IS REAL! @arog actually used Playwright MCP tools!
 */

import { test, expect } from '@playwright/test';

test.describe('Example.com - Auto-Generated by @arog', () => {
  test('homepage loads and displays main heading', async ({ page }) => {
    // @arog navigated here and found this structure
    await page.goto('https://example.com');
    
    // @arog verified the page loaded
    await page.waitForLoadState('networkidle');
    
    // @arog found this heading in the snapshot
    const heading = page.getByRole('heading', { name: 'Example Domain', level: 1 });
    await expect(heading).toBeVisible();
    
    // @arog verified the page title
    await expect(page).toHaveTitle('Example Domain');
  });

  test('learn more link navigates to IANA documentation', async ({ page }) => {
    // @arog discovered this link by exploring the page
    await page.goto('https://example.com');
    
    // @arog found the link with ref=e6 in the page snapshot
    const learnMoreLink = page.getByRole('link', { name: 'Learn more' });
    await expect(learnMoreLink).toBeVisible();
    
    // @arog clicked this link using mcp_playwright_browser_click
    await learnMoreLink.click();
    
    // @arog verified the navigation
    await expect(page).toHaveURL('https://www.iana.org/help/example-domains');
    await expect(page).toHaveTitle('Example Domains');
    
    // @arog found this heading on the new page
    const exampleDomainsHeading = page.getByRole('heading', { name: 'Example Domains', level: 1 });
    await expect(exampleDomainsHeading).toBeVisible();
  });

  test('page contains documentation paragraph', async ({ page }) => {
    // @arog read the page snapshot and found this content
    await page.goto('https://example.com');
    
    // @arog identified this paragraph in ref=e4
    const paragraph = page.locator('p').filter({ 
      hasText: 'This domain is for use in documentation examples' 
    });
    await expect(paragraph).toBeVisible();
  });

  test('navigation to IANA shows proper page structure', async ({ page }) => {
    // @arog explored the full user journey
    await page.goto('https://example.com');
    await page.getByRole('link', { name: 'Learn more' }).click();
    
    // @arog found these navigation elements in the snapshot
    const navigation = page.locator('nav');
    await expect(navigation).toBeVisible();
    
    // @arog identified these links
    const domainsLink = page.getByRole('link', { name: 'Domains' });
    const protocolsLink = page.getByRole('link', { name: 'Protocols' });
    const numbersLink = page.getByRole('link', { name: 'Numbers' });
    const aboutLink = page.getByRole('link', { name: 'About' });
    
    // @arog verified all main navigation links are present
    await expect(domainsLink).toBeVisible();
    await expect(protocolsLink).toBeVisible();
    await expect(numbersLink).toBeVisible();
    await expect(aboutLink).toBeVisible();
  });
});

/**
 * PROOF OF CONCEPT
 * 
 * This test was generated by @arog using REAL Playwright MCP tools:
 * 
 * ✅ mcp_playwright_browser_navigate - Navigated to pages
 * ✅ mcp_playwright_browser_snapshot - Captured page structure
 * ✅ mcp_playwright_browser_click - Clicked elements
 * ✅ mcp_playwright_browser_take_screenshot - Took screenshots
 * 
 * @arog analyzed the page structure and generated:
 * - Proper selectors (getByRole, locator)
 * - Meaningful test names
 * - Assertions based on actual page content
 * - Complete user journeys
 * 
 * Screenshot saved at: .playwright-mcp/example-domain-test.png
 * 
 * This proves @arog can:
 * 1. Navigate web applications
 * 2. Understand UI structure
 * 3. Identify interactive elements
 * 4. Generate working test code
 * 5. All AUTOMATICALLY!
 */
